name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  arm_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Start arm64 runner
        run: |
          curl -vfs https://circleci.com/api/v2/project/gh/jonohill/circle-gh-runner/pipeline \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Circle-Token: ${{ secrets.CCI_TOKEN }}' \
            --data-binary '{ "branch": "main", "parameters": { "GH_REPO": "${{ github.repository }}" } }'

  build:
    runs-on: [self-hosted, linux, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build installer
        run: |
          docker run --privileged --platform linux/arm64 -v /proc:/proc \
            -v "$(pwd):/working_dir" \
            -w /working_dir \
            ubuntu:22.04 \
            ./build-installer.sh
          mkdir -p os/etc/config/packages.chroot
          cp *.deb os/etc/config/packages.chroot

      - name: Build ISO
        run: ./build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: iso
          path: os/builds/arm64/*.iso

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: iso

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            *.iso
