name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run: |
          cp build.conf os/build.conf
          cd os
          docker run --privileged --platform linux/arm64 -v /proc:/proc \
            -v ${PWD}:/working_dir \
            -w /working_dir \
            debian:latest \
            /bin/bash -s build.conf < build.sh
